### PR TITLE
[#25] Creates a simple task service skeleton with an OCR endpoint

### PR DESCRIPTION
**Pull request by lancelafontaine**
[#25]

- [x] Creates a simple task service skeleton with an OCR endpoint

### CODE REVIEW

**Review by Vynny — CHANGES_REQUESTED** [review]
You forgot to add this service to the cjl file

**Comment by lancelafontaine** [comment]
Nice catch, adding now.

**Comment by lancelafontaine** [comment]
Unit tests to come as actual functionality is implemented.

**Review by Vynny — APPROVED** [review]

**Comment by dodoels** [comment]
looks good

**Pull request merged**
