### PR TITLE
[#43] probabilities

### PR DESCRIPTION
**Pull request by Samuel-Campbell**
1) Added probabilities to predictions
2) Model now trains using probabilities = True --> increases training time
3) ReadMe updated with change in end point
4) Probabilities only on Classifiers obviously.

Only once approved
--------------------
- [ ] upload new models on cjl

### CODE REVIEW

**Review by dodoels — COMMENTED** [review]
Why do we need a list of probability ?

**Comment by Samuel-Campbell** [comment]
Everyone telling me mixed stuff but friday we discussed this. When we do a prediction we wanted to give the user it's probability. Answering more questions will increase probability or change the outcome

**Comment by Samuel-Campbell** [comment]
Also what was said: "just give us back as many numbers as you can"

**Review by arekmano — APPROVED** [review]
looks good

**Pull request merged**
