### PR TITLE
[#8] Added new full path methods

### PR DESCRIPTION
**Pull request by arekmano**

### CODE REVIEW

**Comment by arekmano** [comment]
unsure if this is required. Will put on hold for now.

**Comment by TaimoorRana** [comment]
is this to fix the path issue?

**Comment by arekmano** [comment]
apparently it was fixed using lance's fix?

**Review by Samuel-Campbell — APPROVED** [review]
This is the correct way to do it

**Review by dodoels — APPROVED** [review]

**Comment by TaimoorRana** [comment]
yes, it was fixed by Lance.

**Review by dodoels — APPROVED** [review]

**Pull request closed without merging**
