### PR TITLE
[#350] Improved regression prediction for Additional Indemnity Money

### PR DESCRIPTION
**Pull request by arekmano**
Old
===
INFO: R2: 0.78
INFO: Explained Variance: 0.78
INFO: Mean Absolute Error: 471.99
INFO: Mean Squared Error: 831383.89

New
===
INFO: R2: 0.89
INFO: Explained Variance: 0.89
INFO: Mean Absolute Error: 333.64
INFO: Mean Squared Error: 411296.65

### CODE REVIEW

**Comment by Samuel-Campbell** [comment]
0.89 is really good R2. We are missing some facts thus the not so good error

**Review by Samuel-Campbell — APPROVED** [review]

**Review by Samuel-Campbell — CHANGES_REQUESTED** [review]
update models on cjl and update init.py

**Review by dodoels — APPROVED** [review]
LGTM

**Comment by arekmano** [comment]
updated models + filesize

**Review by TaimoorRana — APPROVED** [review]

**Review by Samuel-Campbell — APPROVED** [review]

**Pull request merged**
