### PR TITLE
[#217] Initial Beta Sign up

### PR DESCRIPTION
**Pull request by arekmano**
- Extracted conversation from main chat
- Added Sample conversation flow
- Added state machine for supplying email/question
- TODO: Send question + Email to BE for storage

[Feedback Requested]
[#217]

### CODE REVIEW

**Comment by arekmano** [comment]
image

**Comment by arekmano** [comment]
image

**Comment by dodoels** [comment]
So after I talked to @lancelafontaine we came up with an idea how to have all the codes in our repo with minimum duplication. 

1. instead of making a new directory for duplicated front-end infrastructure, we change the config in the existing infrastructure with an environment variable, let's say `CJL_RELEASE`. We build the page within the infra. When the variable is set to `beta`, the CI/CD is gonna pick up the code and build based on the config (i.e. build the beta landing page ONLY, and ignore all other pages and routing)
2. create `beta_backend_service` with independent database
3. our CD is gonna have two configs: 1) it builds everything on the front-end except the beta page, and builds every service except `beta_backend_service`, and associate to `capstone.cjl.com`; 2) it builds only the beta page on FE and only the `beta_backend_service`, and associate to `procezeus.ca`

@arekmano

**Comment by lancelafontaine** [comment]
Clarification for 3: we would still only have on CI/CD pipeline. Builds would run tests for all services (beta, non-beta) and deploy both to our server.

**Comment by arekmano** [comment]
1. That seems like significant effort for a change that we will essentially "dispose" of. 
2. I think it makes sense to have both the beta page up as well as our application. Beta would be for public, application page would be for demos, internal testing, etc.
3. Configuration + pipeline changes do not add user value IMO and we should stick to what works already.

For these reasons I think it makes sense to decouple them "nearly" entirely, and have the beta be a seperate entity. Something like nginx routing should discriminate what we show users. (e.g. procezeus.ca -> beta page, capstone.cjl -> application)

**Review by dodoels — APPROVED** [review]
Approved and merge now. PR is too big and can't see the difference. I will work on the UI based on this.

**Pull request merged**
