### PR TITLE
[#218] Integration of beta client and server

### PR DESCRIPTION
**Pull request by dodoels**
[#218]

- [x] Integration with back-end
- [x] Validation on answers
- [x] QA

### CODE REVIEW

**Review by arekmano — APPROVED** [review]
seems like isSent variable is not used? otherwise looks good

**Comment by dodoels** [comment]
@arekmano good catch. I dont use IDE so this sometimes easy to miss

**Comment by dodoels** [comment]
@lancelafontaine  will QA this changes and host it if no issue, then I will merge after

**Review by lancelafontaine — APPROVED** [review]
Fixed a few small issues, but I manually tested everything and it seems to work great now. It's ready to be merged and deployed to production.

**Pull request merged**
